# jira_config.yaml â€” edit this file and commit
configs:
#   - name: "ai based github integration"
#     issue_key: "DEV2-1"
  
  - name: "Project A"
    issue_key: "DEV2-2"
  
  # - name: "Project B"
  #   issue_key: "DEV2-3"

  # - name: "Project C"
  # issue_key: "DEV2-4"
